package com.incidentplatform.ai.analysis;

import java.util.List;

/**
 * A validated, grounded analysis: the model's answer after every citation has been checked against
 * the evidence it was actually shown.
 *
 * @param deploymentCorrelation calculated in code, not generated by the model
 * @param sources               every evidence item the model was shown, whether or not it was cited
 * @param grounding             what validation found and changed, so its corrections are visible
 */
public record AnalysisResult(
        AnalysisStatus status,
        String rootCause,
        double confidence,
        List<String> affectedServices,
        List<EvidenceClaim> evidence,
        List<AlternativeHypothesis> alternativeHypotheses,
        List<String> contributingFactors,
        List<String> recommendations,
        List<RelatedIncident> relatedIncidents,
        DeploymentCorrelation deploymentCorrelation,
        List<SourceRef> sources,
        GroundingReport grounding
) {

    public enum AnalysisStatus {
        ROOT_CAUSE_IDENTIFIED,
        INSUFFICIENT_EVIDENCE
    }

    /** @param verified true only when at least one cited reference exists in the evidence shown */
    public record EvidenceClaim(String claim, List<String> sourceRefs, boolean verified) {
    }

    public record AlternativeHypothesis(String hypothesis, String assessment, String reason, List<String> sourceRefs) {
    }

    public record RelatedIncident(String sourceRef, String title, String relevance) {
    }

    public record SourceRef(String ref, String category, String title) {
    }

    public record GroundingReport(
            int claimsTotal,
            int claimsVerified,
            int invalidCitationsRemoved,
            boolean downgradedToInsufficientEvidence,
            boolean confidenceCapped,
            boolean evidenceTruncated,
            List<String> notes
    ) {
    }
}
